db = "/data/freedit.db"
addr = "127.0.0.1:3001"
avatars_path = "/tmp/freedit/static/imgs/avatars"
inn_icons_path = "/tmp/freedit/static/imgs/inn_icons"
upload_path = "/tmp/freedit/static/imgs/upload"
tantivy_path = "tantivy"
proxy = ""
